name: Continuous Integration
on:
  workflow_dispatch: null
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      # Enforce removal of the 'do-not-merge' label before merging
      - name: check readiness for merge
        run: |
          LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
          
          if echo "$LABELS" | grep -q "do-not-merge"; then
            echo "This PR is labeled as 'do-not-merge'. Please make sure it is ready to be merged."
            exit 1
          else
            echo "No 'do-not-merge' label found. Proceeding with merge."
          fi
