name: Labeler

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labeler.yml'
  pull_request:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labeler.yml'
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue

      - name: Check Merge Readiness
        if: github.event_name == 'pull_request'
        run: |
          LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
          
          if echo "$LABELS" | grep -q "do-not-merge"; then
            echo "This PR is labeled as 'do-not-merge'. Please make sure it is ready."
            exit 1
          else
            exit 0
          fi